personality = "pragmatic"
model = "gpt-5.5"
model_reasoning_effort = "medium"
sandbox_mode = "workspace-write"
approvals_reviewer = "user"


notify = ["/Users/ueki/ghq/github.com/uekiGityuto/dotfiles/dot_codex/computer-use/Codex Computer Use.app/Contents/SharedSupport/SkyComputerUseClient.app/Contents/MacOS/SkyComputerUseClient", "turn-ended"]

[mcp_servers.context7]
command = "npx"
args = ["-y", "@upstash/context7-mcp"]

[mcp_servers.node_repl]
args = []
command = "/Applications/Codex.app/Contents/Resources/cua_node/bin/node_repl"
startup_timeout_sec = 120

[mcp_servers.node_repl.env]
NODE_REPL_NATIVE_PIPE_CONNECT_TIMEOUT_MS = "1000"
NODE_REPL_NODE_MODULE_DIRS = "/Applications/Codex.app/Contents/Resources/cua_node/lib/node_modules"
NODE_REPL_NODE_PATH = "/Applications/Codex.app/Contents/Resources/cua_node/bin/node"
NODE_REPL_TRUSTED_CODE_PATHS = "/Users/ueki/.codex"
CODEX_HOME = "/Users/ueki/.codex"
NODE_REPL_TRUSTED_BROWSER_CLIENT_SHA256S = "27dca86fd6b571c49414a4b78e46b57bcf683a46cd1319799c11fbb6cfae3110"
BROWSER_USE_AVAILABLE_BACKENDS = "chrome,iab"
NODE_REPL_INSTRUCTIONS_USE_CASE_BROWSER = "Control the in-app browser in conjunction with the Browser Plugin."
NODE_REPL_INSTRUCTIONS_USE_CASE_CHROME = "Control the Chrome browser in conjunction with the Chrome Plugin. Prefer this method of controlling Chrome over alternatives (such as Computer Use) unless the user explicitly mentions an alternative."
BROWSER_USE_CODEX_APP_BUILD_FLAVOR = "prod"
BROWSER_USE_CODEX_APP_VERSION = "26.609.41114"
CODEX_CLI_PATH = "/Applications/Codex.app/Contents/Resources/codex"

[projects."/Users/ueki/ghq/github.com/uekiGityuto/dotfiles"]
trust_level = "trusted"

[projects."/Users/ueki/ghq/github.com/Finatext/izarra-front"]
trust_level = "trusted"

[projects."/Users/ueki/ghq/github.com/Finatext/orion-front"]
trust_level = "trusted"

[projects."/Users/ueki/ghq/github.com/uekiGityuto/vocabix"]
trust_level = "trusted"

[projects."/Users/ueki/ghq/github.com/uekiGityuto/personal-scripts"]
trust_level = "trusted"

[projects."/Users/ueki/ghq/github.com/uekiGityuto/todo-list"]
trust_level = "trusted"

[projects."/Users/ueki/ghq/github.com/Finatext/liqueur-server"]
trust_level = "trusted"

[projects."/Users/ueki/ghq/github.com/beatnex-tokyo/nsj-proposal"]
trust_level = "trusted"

[projects."/Users/ueki/ghq/github.com/wizenet/nsj"]
trust_level = "trusted"

[projects."/Users/ueki/ghq/github.com/Finatext/liqueur-front"]
trust_level = "trusted"

[notice.model_migrations]
"gpt-5.3-codex" = "gpt-5.4"
"gpt-5.1-codex-max" = "gpt-5.4"

[marketplaces.openai-bundled]
last_updated = "2026-06-13T04:22:38Z"
source_type = "local"
source = "/Users/ueki/ghq/github.com/uekiGityuto/dotfiles/dot_codex/.tmp/bundled-marketplaces/openai-bundled"

[marketplaces.openai-primary-runtime]
last_updated = "2026-06-02T14:39:56Z"
source_type = "local"
source = "/Users/ueki/.cache/codex-runtimes/codex-primary-runtime/plugins/openai-primary-runtime"

[plugins."computer-use@openai-bundled"]
enabled = true

[plugins."github@openai-curated"]
enabled = true

[plugins."documents@openai-primary-runtime"]
enabled = true

[plugins."spreadsheets@openai-primary-runtime"]
enabled = true

[plugins."presentations@openai-primary-runtime"]
enabled = true

[plugins."slack@openai-curated"]
enabled = true

[plugins."figma@openai-curated"]
enabled = true

[plugins."openai-developers@openai-curated"]
enabled = true

[plugins."notion@openai-curated"]
enabled = true

[plugins."browser@openai-bundled"]
enabled = true

[plugins."chrome@openai-bundled"]
enabled = true

[tui.model_availability_nux]
"gpt-5.5" = 4

[hooks.state]

[hooks.state."/Users/ueki/ghq/github.com/wizenet/nsj/.codex/hooks.json:stop:0:0"]
trusted_hash = "sha256:1ed8f0bd045ec0d987827126a1b4b8e31ef4eb2f6b341aea209a590e59725681"

[hooks.state."/Users/ueki/ghq/github.com/wizenet/nsj/.codex/hooks.json:pre_tool_use:0:0"]
trusted_hash = "sha256:87bffe8cb47639132ae70017f9d1daa4fef46c1ed23dc402f71ef6138fbecf04"

[hooks.state."/Users/ueki/ghq/github.com/uekiGityuto/todo-list/.codex/hooks.json:stop:0:0"]
trusted_hash = "sha256:1ed8f0bd045ec0d987827126a1b4b8e31ef4eb2f6b341aea209a590e59725681"

[desktop]
localeOverride = "ja-JP"
preventSleepWhileRunning = true
keepRemoteControlAwakeWhilePluggedIn = true
git-always-force-push = false
git-show-sidebar-pr-icons = true

[desktop.open-in-target-preferences]
global = "vscode"

[desktop.open-in-target-preferences.perPath]
"/Users/ueki/ghq/github.com/wizenet/nsj" = "vscode"

[features]
memories = true

[memories]
generate_memories = true
use_memories = true
