personality = "pragmatic"
model = "gpt-5.3-codex"
model_reasoning_effort = "medium"
sandbox_mode = "workspace-write"

[projects."/Users/ueki/ghq/github.com/uekiGityuto/dotfiles"]
trust_level = "trusted"

[projects."/Users/ueki/ghq/github.com/Finatext/izarra-front"]
trust_level = "trusted"

[projects."/Users/ueki/ghq/github.com/Finatext/orion-front"]
trust_level = "trusted"

[notice.model_migrations]
"gpt-5.3-codex" = "gpt-5.4"
